<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260922062539 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER INDEX uniq_app_user_phone RENAME TO UNIQ_88BDF3E96B01BC5B');
        $this->addSql('ALTER TABLE category ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE category ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX uniq_category_slug RENAME TO UNIQ_64C19C1989D9B62');
        $this->addSql('ALTER INDEX idx_category_parent RENAME TO IDX_64C19C1727ACA70');
        $this->addSql('ALTER TABLE city ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE city ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX idx_city_country RENAME TO IDX_2D5B0234F92F3E70');
        $this->addSql('ALTER TABLE country ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE country ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX uniq_country_code RENAME TO UNIQ_5373C96677153098');
        $this->addSql('ALTER TABLE district ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE district ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX idx_district_city RENAME TO IDX_31C154878BAC62AF');
        $this->addSql('DROP INDEX idx_otp_phone_created');
        $this->addSql('COMMENT ON COLUMN professional_profile.id IS \'\'');
        $this->addSql('ALTER INDEX uniq_professional_profile_user RENAME TO UNIQ_E728A82A76ED395');
        $this->addSql('ALTER INDEX idx_professional_profile_district RENAME TO IDX_E728A82B08FA272');
        $this->addSql('COMMENT ON COLUMN professional_service.id IS \'\'');
        $this->addSql('ALTER INDEX idx_professional_service_professional RENAME TO IDX_6EB8BA5FDB77003');
        $this->addSql('ALTER INDEX idx_professional_service_category RENAME TO IDX_6EB8BA5F12469DE2');
        $this->addSql('ALTER INDEX uniq_refresh_token_hash RENAME TO UNIQ_C74F2195B3BC57DA');
        $this->addSql('ALTER INDEX idx_refresh_token_user RENAME TO IDX_C74F2195A76ED395');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER INDEX uniq_88bdf3e96b01bc5b RENAME TO uniq_app_user_phone');
        $this->addSql('ALTER TABLE category ALTER id SET DEFAULT nextval(\'category_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE category ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX uniq_64c19c1989d9b62 RENAME TO uniq_category_slug');
        $this->addSql('ALTER INDEX idx_64c19c1727aca70 RENAME TO idx_category_parent');
        $this->addSql('ALTER TABLE city ALTER id SET DEFAULT nextval(\'city_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE city ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX idx_2d5b0234f92f3e70 RENAME TO idx_city_country');
        $this->addSql('ALTER TABLE country ALTER id SET DEFAULT nextval(\'country_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE country ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX uniq_5373c96677153098 RENAME TO uniq_country_code');
        $this->addSql('ALTER TABLE district ALTER id SET DEFAULT nextval(\'district_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE district ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX idx_31c154878bac62af RENAME TO idx_district_city');
        $this->addSql('CREATE INDEX idx_otp_phone_created ON otp_challenge (phone_number, created_at)');
        $this->addSql('COMMENT ON COLUMN professional_profile.id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER INDEX uniq_e728a82a76ed395 RENAME TO uniq_professional_profile_user');
        $this->addSql('ALTER INDEX idx_e728a82b08fa272 RENAME TO idx_professional_profile_district');
        $this->addSql('COMMENT ON COLUMN professional_service.id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER INDEX idx_6eb8ba5f12469de2 RENAME TO idx_professional_service_category');
        $this->addSql('ALTER INDEX idx_6eb8ba5fdb77003 RENAME TO idx_professional_service_professional');
        $this->addSql('ALTER INDEX idx_c74f2195a76ed395 RENAME TO idx_refresh_token_user');
        $this->addSql('ALTER INDEX uniq_c74f2195b3bc57da RENAME TO uniq_refresh_token_hash');
    }
}
